/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package filtrandodatosporcombo;

import filtrandodatosporcombo.dao.ComboAreaDAO;
import filtrandodatosporcombo.dao.ComboSeccionDAO;
import filtrandodatosporcombo.dao.EmpleadoDAO;
import filtrandodatosporcombo.modelo.ComboArea;
import filtrandodatosporcombo.modelo.ComboSeccion;
import filtrandodatosporcombo.modelo.Empleado;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ListaEmpleados extends javax.swing.JFrame {

    private ComboAreaDAO daoComboArea;
    private ComboSeccionDAO daoComboSeccion;
    private EmpleadoDAO daoEmpleado;

    /**
     * Creates new form ListaEmpleados
     */
    public ListaEmpleados() {
        initComponents();

        daoComboArea = new ComboAreaDAO();
        daoComboSeccion = new ComboSeccionDAO();
        daoEmpleado = new EmpleadoDAO();

        cargarComboBoxArea();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areasCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        seccionesCombo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleado = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areasCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                areasComboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                areasComboMouseEntered(evt);
            }
        });

        jLabel1.setText("Areas");

        jLabel2.setText("Secciones");

        seccionesCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seccionesComboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seccionesComboMouseEntered(evt);
            }
        });

        tablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CI", "Nombre", "Apellido"
            }
        ));
        jScrollPane1.setViewportView(tablaEmpleado);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Empleados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(areasCombo, 0, 136, Short.MAX_VALUE)
                    .addComponent(seccionesCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(237, 237, 237))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seccionesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarComboBoxArea() {
        areasCombo.removeAllItems();
        Vector<ComboArea> oListaObjetoParaComboBoxArea = daoComboArea.ListaDeObjetosParaComboBoxArea();

        for (int i = 0; i < oListaObjetoParaComboBoxArea.size(); i = i + 1) {
            ComboArea oItem = new ComboArea(oListaObjetoParaComboBoxArea.get(i).getId_area(), oListaObjetoParaComboBoxArea.get(i).getDescripcion());

            areasCombo.addItem(oItem);
            
            // areasCombo.addItem(oItem.getId_area()+" "+oItem.getDescripcion());
        }
    }
    

    private void areasComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areasComboMouseClicked
        // TODO add your handling code here:

        
    }//GEN-LAST:event_areasComboMouseClicked

    private void areasComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areasComboMouseEntered
        // TODO add your handling code here:
        ComboArea olistaAreas = (ComboArea) areasCombo.getSelectedItem();

        int areaId = olistaAreas.getId_area();

        // System.out.println("EL ID ES---> "+areaId);

        seccionesCombo.removeAllItems();
        Vector<ComboSeccion> oListaObjetoParaComboBoxSeccion = daoComboSeccion.ListaDeObjetosParaComboBoxSeccionByIdArea(areaId);

        for (int i = 0; i < oListaObjetoParaComboBoxSeccion.size(); i = i + 1) {
            ComboSeccion oItem = new ComboSeccion(oListaObjetoParaComboBoxSeccion.get(i).getId_seccion(), oListaObjetoParaComboBoxSeccion.get(i).getDescripcion());

            // seccionesCombo.addItem(oItem.getId_seccion()+" "+oItem.getDescripcion());
            seccionesCombo.addItem(oItem);

        }
    }//GEN-LAST:event_areasComboMouseEntered

    private void seccionesComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seccionesComboMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_seccionesComboMouseClicked

    private void seccionesComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seccionesComboMouseEntered
        // TODO add your handling code here:
        ComboSeccion olistaSecciones = (ComboSeccion) seccionesCombo.getSelectedItem();

        int seccionId = olistaSecciones.getId_seccion();

        System.out.println("EL ID ES---> "+seccionId);
        
        // System.out.println("EL ID ES---> "+areaId);

        DefaultTableModel modelo = (DefaultTableModel)  tablaEmpleado.getModel(); 
        modelo.setRowCount(0);
        
        List<Empleado> empleados = new ArrayList<Empleado>();
        empleados = daoEmpleado.listarEmpleadosByIdSeccion(seccionId);
        
        for (int i = 0; i < empleados.size(); i = i+1)
        {   
            Empleado empl= new Empleado();
            empl=empleados.get(i);
            
            modelo.addRow( new Object[]{
                    empl.getCi(), empl.getNombre(),
                    empl.getApellido() });
       }
    }//GEN-LAST:event_seccionesComboMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaEmpleados().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox areasCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox seccionesCombo;
    private javax.swing.JTable tablaEmpleado;
    // End of variables declaration//GEN-END:variables
}
